### ISSUE TITLE
binding cache appears to be not working

### ISSUE THREAD

**Issue by patrickelectric** [mauricek/qtwasm_builder#5]
It appears that `-v ~/.emscripten_cache2:/root/.emscripten_cache` is not working and everything is being build from scratch. Can this be confirmed ?

**Comment by mauricek** [comment]
So you are trying to have a local cache being exposed to the running instance?
I'll try that out, didn't think about that way so far.

**Comment by patrickelectric** [comment]
Hi @mauricek, the idea is to have a local cache folder to allow faster builds for the docker.

**Comment by mauricek** [comment]
docker run --rm -v $PWD:/project/source -v $PWD:/project/build -v ~/asmcache:/root/.emscripten_cache maukalinow/qtwasm_builder:5.13_latest

Seems to work nicely for me, creating cache on first run, and re-using it on the second.
Would you be able to provide some more details? Which docker version on which OS? Are there any errors being displayed?

Is the directory correctly mounted when you run it interactively? Meaning, does it really take that directory as cache?

**Comment by mauricek** [comment]
Closing due to missing feedback. If this reoccurs, please re-open.
